CREATE TABLE "locations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "type" varchar(20) NOT NULL,
  "address" text,
  "city" varchar(50),
  "state" varchar(50),
  "country" varchar(50) DEFAULT 'Belize',
  "latitude" decimal(10,8),
  "longitude" decimal(11,8),
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "user_type" varchar(20) NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "customers" (
  "id" int PRIMARY KEY,
  "phone_number" varchar(20),
  "address" text,
  "date_of_birth" date,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "tellers" (
  "id" int PRIMARY KEY,
  "employee_id" varchar(20) UNIQUE NOT NULL,
  "terminal_location_id" int,
  "commission_rate" decimal(5,2) DEFAULT 0.05,
  "is_authorized" boolean DEFAULT false,
  "hire_date" date,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "buses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "bus_number" varchar(20) UNIQUE NOT NULL,
  "type" varchar(20) NOT NULL,
  "seat_capacity" int NOT NULL,
  "available_seats" int NOT NULL,
  "departure_location_id" int,
  "arrival_location_id" int,
  "departure_time" time,
  "arrival_time" time,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "bus_stops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bus_id" int,
  "location_id" int,
  "stop_order" int,
  "arrival_time" time,
  "departure_time" time
);

CREATE TABLE "tickets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bus_id" int,
  "customer_id" int,
  "teller_id" int,
  "destination" varchar(100) NOT NULL,
  "travel_date" date NOT NULL,
  "booking_date" timestamp DEFAULT (now()),
  "number_of_seats" int,
  "price_per_seat" decimal(10,2),
  "total_price" decimal(10,2),
  "status" varchar(20) DEFAULT 'Booked',
  "seat_numbers" varchar(100),
  "booking_reference" varchar(20) UNIQUE,
  "is_round_trip" boolean DEFAULT false,
  "return_date" date,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "customer_bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "ticket_id" int,
  "booking_date" timestamp DEFAULT (now())
);

CREATE TABLE "teller_sales" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teller_id" int,
  "ticket_id" int,
  "sale_date" timestamp DEFAULT (now())
);

CREATE TABLE "system_config" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "config_key" varchar(50) UNIQUE NOT NULL,
  "config_value" text,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE UNIQUE INDEX ON "teller_sales" ("teller_id", "ticket_id");

COMMENT ON TABLE "locations" IS 'All bus terminals, stops, cities, and towns';

COMMENT ON TABLE "users" IS 'Base table for customers and tellers';

COMMENT ON TABLE "customers" IS 'Customer specific data';

COMMENT ON TABLE "tellers" IS 'Employees who sell tickets';

COMMENT ON TABLE "buses" IS 'Buses and their schedules';

COMMENT ON TABLE "bus_stops" IS 'Intermediate stops for each bus route';

COMMENT ON TABLE "tickets" IS 'Ticket bookings for bus travel';

COMMENT ON TABLE "customer_bookings" IS 'History of all bookings made by customers';

COMMENT ON TABLE "teller_sales" IS 'Tracks ticket sales made by tellers';

COMMENT ON TABLE "system_config" IS 'System configuration values';

ALTER TABLE "customers" ADD FOREIGN KEY ("id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tellers" ADD FOREIGN KEY ("id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tellers" ADD FOREIGN KEY ("terminal_location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "buses" ADD FOREIGN KEY ("departure_location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "buses" ADD FOREIGN KEY ("arrival_location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bus_stops" ADD FOREIGN KEY ("bus_id") REFERENCES "buses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bus_stops" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("bus_id") REFERENCES "buses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("teller_id") REFERENCES "tellers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customer_bookings" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customer_bookings" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "teller_sales" ADD FOREIGN KEY ("teller_id") REFERENCES "tellers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "teller_sales" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;
